import { DeliverableId } from '../contracts';

export interface PromptContext {
  buildTranscript: string;
  intakeTranscript?: string;
  operatorNotes?: string;
  settings: {
    cta_mode: string;
    audience_temperature: string;
    webinar_length_minutes: number;
  };
  dependencies?: Record<string, unknown>;
}

export function getConstraintSummary(deliverableId: DeliverableId): string {
  const summaries: Record<DeliverableId, string> = {
    PREFLIGHT: `{
  "status": "can_proceed" | "blocked",
  "readiness": { "score": 0-100, "rationale": "string" },
  "missing_context": [{ "field": "string", "why_it_matters": "string", "example_answer": "string" }],
  "assumptions": ["string"],
  "recommended_questions": ["string"]
}`,
    WR1: `{
  "parsed_intake": {
    "client_name": "string" | null,
    "company": "string" | null,
    "webinar_title": "string" | null,
    "offer": "string" | null,
    "target_audience": "string" | null,
    "tone": "string" | null,
    "primary_cta_type": "book_call" | "buy_now" | "hybrid" | null,
    "speaker_name": "string" | null,
    "speaker_title": "string" | null
  },
  "executive_summary": {
    "overview": "string (2-3 sentence strategic overview of the webinar opportunity)",
    "key_points": ["string (3-5 key strategic points)"]
  },
  "cleaned_transcript": "string",
  "structured_notes": ["string"],
  "main_themes": ["string"],
  "speaker_insights": ["string"],
  "proof_points": [{ "type": "testimonial" | "metric" | "case_study", "content": "string", "source": "string" | null }],
  "qa": { "assumptions": [], "placeholders": [], "claims_requiring_proof": [] }
}`,
    WR2: `EXACTLY 21 blocks array. Block IDs MUST be: B01, B02, B03, B04, B05, B06, B07, B08, B09, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20, B21
Phase mapping: B01-B07="beginning", B08-B14="middle", B15-B21="end"
Each block: { block_id, phase, title, purpose, talk_track_md, speaker_notes_md, transition_in, transition_out, timebox_minutes (1-60), proof_insertion_points[], objections_handled[] }
qa: { assumptions: [], placeholders: [], claims_requiring_proof: [] }`,
    WR3: `{
  "hero_headline": "string",
  "subheadline": "string",
  "bullets": ["string"] (3-7 items),
  "agenda_preview": [{ "segment": "string", "timebox_minutes": number, "promise": "string" }],
  "proof_blocks": [{ "type": "testimonial" | "metric" | "case_study", "content": "string", "needs_source": boolean }],
  "speaker_bio": { "one_liner": "string", "credibility_bullets": ["string"] },
  "cta_block": { "headline": "string", "body": "string", "button_label": "string", "link_placeholder": "string" },
  "faq": [{ "question": "string", "answer": "string" }],
  "who_its_for": ["string"],
  "who_its_not_for": ["string"],
  "legal_disclaimer_md": "string",
  "qa": { "assumptions": [], "placeholders": [], "claims_requiring_proof": [] }
}`,
    WR4: `email_id format: E01, E02, E03, E04, E05, E06, E07, E08, E09, E10 (MUST use two digits with leading zero)
8-10 emails required
Each email: { email_id, timing, subject, preview_text, body_markdown, primary_cta_label, primary_cta_link_placeholder }
send_rules: { from_name_placeholder, from_email_placeholder, reply_to_placeholder }
qa: { assumptions: [], placeholders: [], claims_requiring_proof: [] }`,
    WR5: `linkedin_posts: 3-8 posts, social_id MUST be S01, S02, S03, S04, S05, S06, S07, or S08
x_posts: 2-6 posts, social_id MUST be S09, S10, S11, S12, S13, or S14
last_chance_blurbs: 1-4 posts, social_id MUST be S15, S16, S17, or S18
Each linkedin_post: { social_id, hook, body, cta_line }
Each x_post: { social_id, body }
Each last_chance_blurb: { social_id, body }
qa: { assumptions: [], placeholders: [], claims_requiring_proof: [] }`,
    WR6: `{
  "total_duration_minutes": 15-180,
  "timeline": [{ "start_minute": number, "end_minute": number, "segment_title": "string", "block_id": "B01"-"B21", "description": "string", "coach_cue": "string", "fallback_if_cold": "string", "time_check": "string" }],
  "qa": { "assumptions": [], "placeholders": [], "claims_requiring_proof": [] }
}`,
    WR7: `checklist_id format MUST use 3 digits: CL_pre_001, CL_pre_002, CL_live_001, CL_live_002, CL_post_001, CL_post_002
pre_webinar items use CL_pre_XXX, live_webinar items use CL_live_XXX, post_webinar items use CL_post_XXX
Each item: { checklist_id, task, timing, notes }
qa: { assumptions: [], placeholders: [], claims_requiring_proof: [] }`,
    WR8: `{
  "gamma_prompt": "string (MUST be at least 100 characters)",
  "slide_count_recommendation": 5-50,
  "visual_direction": "string",
  "key_slides": [{ "slide_number": number, "title": "string", "purpose": "string", "content_points": ["string"] }],
  "qa": { "assumptions": [], "placeholders": [], "claims_requiring_proof": [] }
}`,
    WR9: 'Computed deterministically, not generated by AI',
  };

  return summaries[deliverableId] || 'No constraint summary available';
}

export function buildSystemPrompt(deliverableId: DeliverableId): string {
  const basePrompt = `You are an expert webinar content strategist outputting STRICT JSON.

CRITICAL RULES - VIOLATIONS WILL CAUSE ERRORS:
1. Output ONLY valid JSON - no markdown fences, no commentary, no explanations before or after
2. Use snake_case for ALL field names (never camelCase)
3. Do NOT add ANY extra fields not specified in the schema - extra fields cause validation failure
4. EVERY deliverable MUST include the "qa" object with exactly: {"assumptions": [], "placeholders": [], "claims_requiring_proof": []}
5. All placeholder strings should use descriptive names ending in "_placeholder"
6. IDs MUST use exact format with leading zeros (E01 not E1, B01 not B1, S01 not S1, CL_pre_001 not CL_pre_1)

REQUIRED SCHEMA:
${getConstraintSummary(deliverableId)}`;

  return basePrompt;
}

export function buildUserPrompt(
  deliverableId: DeliverableId,
  context: PromptContext
): string {
  const prompts: Record<DeliverableId, (ctx: PromptContext) => string> = {
    PREFLIGHT: (ctx) => `Analyze the following webinar content for readiness:

BUILD TRANSCRIPT:
${ctx.buildTranscript.slice(0, 5000)}...

${ctx.intakeTranscript ? `INTAKE TRANSCRIPT:\n${ctx.intakeTranscript.slice(0, 2000)}...\n\n` : ''}${ctx.operatorNotes ? `OPERATOR NOTES:\n${ctx.operatorNotes}\n\n` : ''}
Return JSON with EXACTLY this structure:
{
  "status": "can_proceed",
  "readiness": { "score": 75, "rationale": "explanation here" },
  "missing_context": [],
  "assumptions": ["assumption 1"],
  "recommended_questions": ["question 1"]
}

Do NOT include risk_flags - those are added deterministically.`,

    WR1: (ctx) => `Extract and normalize webinar intake data.

BUILD TRANSCRIPT:
${ctx.buildTranscript}

${ctx.intakeTranscript ? `INTAKE TRANSCRIPT:\n${ctx.intakeTranscript}\n\n` : ''}${ctx.operatorNotes ? `OPERATOR NOTES:\n${ctx.operatorNotes}\n\n` : ''}
Return JSON with EXACTLY this structure (use null for any missing values):
{
  "parsed_intake": {
    "client_name": "Name" or null,
    "company": "Company" or null,
    "webinar_title": "Title" or null,
    "offer": "Description of offer" or null,
    "target_audience": "Description" or null,
    "tone": "professional/casual/etc" or null,
    "primary_cta_type": "book_call" or "buy_now" or "hybrid" or null,
    "speaker_name": "Name" or null,
    "speaker_title": "Title" or null
  },
  "executive_summary": {
    "overview": "2-3 sentence strategic overview of the webinar opportunity, positioning, and unique value proposition",
    "key_points": [
      "Key strategic point 1",
      "Key strategic point 2",
      "Key strategic point 3"
    ]
  },
  "cleaned_transcript": "cleaned transcript text here",
  "structured_notes": ["note 1", "note 2"],
  "main_themes": ["theme 1", "theme 2", "theme 3"],
  "speaker_insights": ["insight about speaker"],
  "proof_points": [
    { "type": "metric", "content": "40% increase in sales", "source": "Case study" },
    { "type": "testimonial", "content": "Great results", "source": null }
  ],
  "qa": {
    "assumptions": ["assumption made"],
    "placeholders": ["placeholder used"],
    "claims_requiring_proof": ["claim that needs verification"]
  }
}

IMPORTANT:
- executive_summary.overview should be a compelling 2-3 sentence summary that captures the webinar's strategic positioning
- executive_summary.key_points should contain 3-5 actionable strategic insights
- primary_cta_type MUST be exactly one of: "book_call", "buy_now", "hybrid", or null
- proof_points type MUST be exactly one of: "testimonial", "metric", "case_study"
- proof_points MUST have "content" field (NOT "point" or "text")`,

    WR2: (ctx) => {
      const targetMinutes = ctx.settings.webinar_length_minutes;
      const avgBlockTime = Math.round(targetMinutes / 21);

      return `Generate Framework 21 content structure.

CRITICAL REQUIREMENTS:
- You MUST generate EXACTLY 21 blocks, no more, no less
- Block IDs MUST be exactly: B01, B02, B03, B04, B05, B06, B07, B08, B09, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20, B21
- Phase mapping is STRICT:
  - B01, B02, B03, B04, B05, B06, B07 = "beginning"
  - B08, B09, B10, B11, B12, B13, B14 = "middle"
  - B15, B16, B17, B18, B19, B20, B21 = "end"
- Total duration: ${targetMinutes} minutes (average ~${avgBlockTime} min per block)
- CTA mode: ${ctx.settings.cta_mode}
- Audience temperature: ${ctx.settings.audience_temperature}

BUILD TRANSCRIPT:
${ctx.buildTranscript.slice(0, 8000)}...

${ctx.operatorNotes ? `OPERATOR NOTES:\n${ctx.operatorNotes}\n\n` : ''}

Return JSON with this EXACT structure containing ALL 21 blocks:
{
  "blocks": [
    {
      "block_id": "B01",
      "phase": "beginning",
      "title": "Opening Hook",
      "purpose": "Capture attention and set expectations",
      "talk_track_md": "Detailed talk track in markdown...",
      "speaker_notes_md": "Speaker notes in markdown...",
      "transition_in": "Welcome everyone...",
      "transition_out": "Now let me share...",
      "timebox_minutes": ${avgBlockTime},
      "proof_insertion_points": ["where to insert proof"],
      "objections_handled": ["objection addressed"]
    },
    {
      "block_id": "B02",
      "phase": "beginning",
      "title": "...",
      ...
    },
    ... continue for B03-B21 ...
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

CRITICAL: You MUST output all 21 blocks from B01 to B21. Missing blocks will cause validation failure.`;
    },

    WR3: (ctx) => `Generate landing page copy.

WR1 DATA:
${JSON.stringify(ctx.dependencies?.WR1 || {}, null, 2).slice(0, 2000)}

WR2 FRAMEWORK:
${JSON.stringify(ctx.dependencies?.WR2 || {}, null, 2).slice(0, 3000)}

Return JSON with EXACTLY this structure:
{
  "hero_headline": "Compelling headline here",
  "subheadline": "Supporting subheadline",
  "bullets": ["Benefit 1", "Benefit 2", "Benefit 3"],
  "agenda_preview": [
    { "segment": "Opening", "timebox_minutes": 5, "promise": "What attendees will learn" },
    { "segment": "Core Content", "timebox_minutes": 30, "promise": "The main value" }
  ],
  "proof_blocks": [
    { "type": "testimonial", "content": "Quote here", "needs_source": true },
    { "type": "metric", "content": "40% improvement", "needs_source": false }
  ],
  "speaker_bio": {
    "one_liner": "Expert in X with Y years experience",
    "credibility_bullets": ["Credential 1", "Credential 2"]
  },
  "cta_block": {
    "headline": "Register Now",
    "body": "Don't miss this opportunity",
    "button_label": "Save My Spot",
    "link_placeholder": "link_placeholder"
  },
  "faq": [
    { "question": "Common question?", "answer": "Clear answer" }
  ],
  "who_its_for": ["Ideal attendee 1", "Ideal attendee 2"],
  "who_its_not_for": ["Not for this person"],
  "legal_disclaimer_md": "Results may vary...",
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

CRITICAL:
- agenda_preview items MUST have: segment, timebox_minutes (number), promise
- speaker_bio MUST have: one_liner (string), credibility_bullets (array)
- proof_blocks type MUST be: "testimonial", "metric", or "case_study"
- bullets array MUST have 3-7 items`,

    WR4: (ctx) => `Generate email campaign sequence.

WR1 DATA:
${JSON.stringify(ctx.dependencies?.WR1 || {}, null, 2).slice(0, 2000)}

CRITICAL: email_id MUST use two-digit format with leading zero: E01, E02, E03, E04, E05, E06, E07, E08, E09, E10
NOT: E1, E2, E3... - single digits will cause validation failure!

Return JSON with EXACTLY this structure:
{
  "send_rules": {
    "from_name_placeholder": "from_name_placeholder",
    "from_email_placeholder": "from_email_placeholder",
    "reply_to_placeholder": "reply_to_placeholder"
  },
  "emails": [
    {
      "email_id": "E01",
      "timing": "T-7 days",
      "subject": "Subject line here",
      "preview_text": "Preview text here",
      "body_markdown": "Email body in markdown format",
      "primary_cta_label": "Register Now",
      "primary_cta_link_placeholder": "primary_cta_link_placeholder"
    },
    {
      "email_id": "E02",
      "timing": "T-5 days",
      ...
    },
    {
      "email_id": "E03",
      ...
    },
    ... continue for E04, E05, E06, E07, E08 (and optionally E09, E10) ...
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

Generate 8-10 emails with IDs E01 through E08/E09/E10.
Each email MUST have ALL fields: email_id, timing, subject, preview_text, body_markdown, primary_cta_label, primary_cta_link_placeholder`,

    WR5: (ctx) => `Generate social media content.

WR1 DATA:
${JSON.stringify(ctx.dependencies?.WR1 || {}, null, 2).slice(0, 2000)}

CRITICAL ID REQUIREMENTS:
- linkedin_posts: Use S01, S02, S03, S04, S05, S06, S07, S08 ONLY (NOT S1, S2...)
- x_posts: Use S09, S10, S11, S12, S13, S14 ONLY
- last_chance_blurbs: Use S15, S16, S17, S18 ONLY

Return JSON with EXACTLY this structure:
{
  "linkedin_posts": [
    { "social_id": "S01", "hook": "Attention grabber", "body": "Post content", "cta_line": "Link in comments" },
    { "social_id": "S02", "hook": "...", "body": "...", "cta_line": "..." },
    { "social_id": "S03", "hook": "...", "body": "...", "cta_line": "..." }
  ],
  "x_posts": [
    { "social_id": "S09", "body": "Tweet content under 280 chars" },
    { "social_id": "S10", "body": "..." }
  ],
  "last_chance_blurbs": [
    { "social_id": "S15", "body": "Urgency message" }
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

REQUIREMENTS:
- linkedin_posts: 3-8 posts with social_id S01-S08, each with hook, body, cta_line
- x_posts: 2-6 posts with social_id S09-S14, each with body only
- last_chance_blurbs: 1-4 posts with social_id S15-S18, each with body only`,

    WR6: (ctx) => `Generate run-of-show timeline.

WR2 FRAMEWORK:
${JSON.stringify(ctx.dependencies?.WR2 || {}, null, 2)}

Return JSON with EXACTLY this structure:
{
  "total_duration_minutes": ${ctx.settings.webinar_length_minutes},
  "timeline": [
    {
      "start_minute": 0,
      "end_minute": 3,
      "segment_title": "Opening",
      "block_id": "B01",
      "description": "What happens in this segment",
      "coach_cue": "Coaching note for presenter",
      "fallback_if_cold": "What to do if audience is unresponsive",
      "time_check": "On time / 2 min buffer"
    },
    {
      "start_minute": 3,
      "end_minute": 6,
      "segment_title": "...",
      "block_id": "B02",
      ...
    }
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

CRITICAL:
- total_duration_minutes MUST equal ${ctx.settings.webinar_length_minutes}
- block_id MUST reference blocks from WR2 (B01-B21 only)
- Timeline segments MUST NOT exceed total_duration_minutes
- Each segment MUST have ALL fields: start_minute, end_minute, segment_title, block_id, description, coach_cue, fallback_if_cold, time_check`,

    WR7: (ctx) => `Generate execution checklist.

CRITICAL: checklist_id MUST use 3-digit format:
- pre_webinar items: CL_pre_001, CL_pre_002, CL_pre_003...
- live_webinar items: CL_live_001, CL_live_002, CL_live_003...
- post_webinar items: CL_post_001, CL_post_002, CL_post_003...
NOT: CL_pre_1, CL_live_1 - single digits will cause validation failure!

Return JSON with EXACTLY this structure:
{
  "pre_webinar": [
    { "checklist_id": "CL_pre_001", "task": "Set up registration page", "timing": "T-7 days", "notes": "Include UTM tracking" },
    { "checklist_id": "CL_pre_002", "task": "Schedule email sequence", "timing": "T-7 days", "notes": "Load into ESP" },
    { "checklist_id": "CL_pre_003", "task": "Test webinar platform", "timing": "T-2 days", "notes": "Check audio/video" }
  ],
  "live_webinar": [
    { "checklist_id": "CL_live_001", "task": "Open room 15 min early", "timing": "-15 min", "notes": "Greet early attendees" },
    { "checklist_id": "CL_live_002", "task": "Start recording", "timing": "0:00", "notes": "Confirm recording indicator" }
  ],
  "post_webinar": [
    { "checklist_id": "CL_post_001", "task": "Send replay email", "timing": "T+1 day", "notes": "Include highlights" },
    { "checklist_id": "CL_post_002", "task": "Follow up with attendees", "timing": "T+2 days", "notes": "Segment by engagement" }
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

Each item MUST have: checklist_id (3-digit format), task, timing, notes`,

    WR8: (ctx) => `Generate Gamma deck prompt.

WR2 FRAMEWORK:
${JSON.stringify(ctx.dependencies?.WR2 || {}, null, 2).slice(0, 5000)}

Return JSON with EXACTLY this structure:
{
  "gamma_prompt": "Create a professional presentation deck for a webinar about [topic]. The deck should have a modern, clean design with [color scheme]. Include slides for: opening hook, problem identification, solution introduction, key benefits, social proof, case studies, FAQ, and call to action. Use high-quality stock imagery and maintain consistent branding throughout. The presentation should feel premium and engaging, with clear visual hierarchy and minimal text per slide.",
  "slide_count_recommendation": 25,
  "visual_direction": "Modern, professional design with blue accents and clean typography",
  "key_slides": [
    {
      "slide_number": 1,
      "title": "Opening Hook",
      "purpose": "Capture attention immediately",
      "content_points": ["Bold statement", "Compelling question"]
    },
    {
      "slide_number": 2,
      "title": "The Problem",
      "purpose": "Identify pain points",
      "content_points": ["Pain point 1", "Pain point 2"]
    }
  ],
  "qa": {
    "assumptions": [],
    "placeholders": [],
    "claims_requiring_proof": []
  }
}

CRITICAL:
- gamma_prompt MUST be at least 100 characters (the example above is exactly 100+ chars)
- slide_count_recommendation MUST be between 5 and 50
- Generate at least 5-10 key_slides`,

    WR9: () => 'WR9 is computed deterministically, not generated by AI.',
  };

  const promptFn = prompts[deliverableId];
  return promptFn ? promptFn(context) : 'No prompt available for this deliverable.';
}

export function buildExecutiveSummaryPrompt(buildTranscript: string, parsedIntake: Record<string, unknown>): {
  system: string;
  user: string;
} {
  const system = `You are an expert webinar content strategist. Generate ONLY a JSON executive summary object.

OUTPUT FORMAT:
{
  "executive_summary": {
    "overview": "2-3 sentence strategic overview",
    "key_points": ["point 1", "point 2", "point 3"]
  }
}

RULES:
1. Output ONLY valid JSON - no markdown fences, no commentary
2. overview must be 2-3 compelling sentences about the webinar's strategic positioning
3. key_points must contain 3-5 actionable strategic insights`;

  const user = `Generate an executive summary for this webinar.

PARSED INTAKE DATA:
${JSON.stringify(parsedIntake, null, 2)}

BUILD TRANSCRIPT:
${buildTranscript.slice(0, 6000)}

Return ONLY the JSON object with executive_summary containing overview and key_points.`;

  return { system, user };
}
